# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-11 23:12
from __future__ import unicode_literals

import django.contrib.sites.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0010_layer_disable_arcgis_attributes'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='layer',
            managers=[
                ('objects', django.contrib.sites.managers.CurrentSiteManager('site')),
            ],
        ),
        migrations.AlterModelManagers(
            name='theme',
            managers=[
                ('objects', django.contrib.sites.managers.CurrentSiteManager('site')),
            ],
        ),
        migrations.AlterField(
            model_name='dataneed',
            name='themes',
            field=models.ManyToManyField(blank=True, to='data_manager.Theme'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='arcgis_layers',
            field=models.CharField(blank=True, help_text='comma separated list of arcgis layer IDs', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='layer',
            name='attribute_event',
            field=models.CharField(choices=[('click', 'click'), ('mouseover', 'mouseover')], default='click', max_length=35),
        ),
        migrations.AlterField(
            model_name='layer',
            name='attribute_fields',
            field=models.ManyToManyField(blank=True, to='data_manager.AttributeInfo'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='bookmark',
            field=models.CharField(blank=True, help_text='link to view data layer in the planner', max_length=755, null=True),
        ),
        migrations.AlterField(
            model_name='layer',
            name='connect_companion_layers_to',
            field=models.ManyToManyField(blank=True, help_text='Select which main layer(s) you would like to use in conjuction with this companion layer.', related_name='_layer_connect_companion_layers_to_+', to='data_manager.Layer'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='data_download',
            field=models.CharField(blank=True, help_text='link to download the data', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='layer',
            name='disable_arcgis_attributes',
            field=models.BooleanField(default=False, help_text='Click to disable clickable ArcRest layers'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='has_companion',
            field=models.BooleanField(default=False, help_text='Check if this layer has a companion layer'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='is_disabled',
            field=models.BooleanField(default=False, help_text='when disabled, the layer will still appear in the TOC, only disabled'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='kml',
            field=models.CharField(blank=True, help_text='link to download the KML', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='layer',
            name='layer_type',
            field=models.CharField(choices=[('XYZ', 'XYZ'), ('WMS', 'WMS'), ('ArcRest', 'ArcRest'), ('radio', 'radio'), ('checkbox', 'checkbox'), ('Vector', 'Vector'), ('placeholder', 'placeholder')], help_text='use placeholder to temporarily remove layer from TOC', max_length=50),
        ),
        migrations.AlterField(
            model_name='layer',
            name='learn_more',
            field=models.CharField(blank=True, help_text='link to view description in the Learn section', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='layer',
            name='legend',
            field=models.CharField(blank=True, help_text='URL or path to the legend image file', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='layer',
            name='legend_title',
            field=models.CharField(blank=True, help_text='alternative to using the layer name', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='layer',
            name='lookup_table',
            field=models.ManyToManyField(blank=True, to='data_manager.LookupInfo'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='map_tiles',
            field=models.CharField(blank=True, help_text='internal link to a page that details how others might consume the data', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='layer',
            name='metadata',
            field=models.CharField(blank=True, help_text='link to view/download the metadata', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='layer',
            name='mouseover_field',
            field=models.CharField(blank=True, help_text='feature level attribute used in mouseover display', max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='layer',
            name='order',
            field=models.PositiveSmallIntegerField(blank=True, default=10, help_text='input an integer to determine the priority/order of the layer being displayed (1 being the highest)', null=True),
        ),
        migrations.AlterField(
            model_name='layer',
            name='point_radius',
            field=models.IntegerField(blank=True, help_text='Used only for for Point layers (default is 2)', null=True),
        ),
        migrations.AlterField(
            model_name='layer',
            name='search_query',
            field=models.BooleanField(default=False, help_text='Select when layers are queryable - e.g. MDAT and CAS'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='shareable_url',
            field=models.BooleanField(default=True, help_text='Indicates whether the data layer (e.g. map tiles) can be shared with others (through the Map Tiles Link)'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='source',
            field=models.CharField(blank=True, help_text='link back to the data source', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='layer',
            name='sublayers',
            field=models.ManyToManyField(blank=True, related_name='_layer_sublayers_+', to='data_manager.Layer'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='themes',
            field=models.ManyToManyField(blank=True, to='data_manager.Theme'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='thumbnail',
            field=models.URLField(blank=True, help_text='not sure we are using this any longer...', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='layer',
            name='wms_version',
            field=models.CharField(blank=True, help_text='WMS Versioning - usually either 1.1.1 or 1.3.0', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='lookupinfo',
            name='dashstyle',
            field=models.CharField(choices=[('dot', 'dot'), ('dash', 'dash'), ('dashdot', 'dashdot'), ('longdash', 'longdash'), ('longdashdot', 'longdashdot'), ('solid', 'solid')], default='solid', max_length=11),
        ),
        migrations.AlterField(
            model_name='theme',
            name='order',
            field=models.PositiveSmallIntegerField(blank=True, default=10, help_text='input an integer to determine the priority/order of the layer being displayed (1 being the highest)', null=True),
        ),
    ]
