# Generated by Django 2.2.10 on 2020-02-12 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0033_layer_show_legend'),
        ('data_manager', '0011_auto_20170311_1512'),
    ]

    operations = [
    ]
