# Generated by Django 2.2.10 on 2020-02-12 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0034_merge_20200212_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layer',
            name='layer_type',
            field=models.CharField(choices=[('XYZ', 'XYZ'), ('WMS', 'WMS'), ('ArcRest', 'ArcRest'), ('radio', 'radio'), ('checkbox', 'checkbox'), ('Vector', 'Vector'), ('VectorTile', 'VectorTile'), ('placeholder', 'placeholder')], help_text='use placeholder to temporarily remove layer from TOC', max_length=50),
        ),
        migrations.AlterField(
            model_name='layer',
            name='learn_more',
            field=models.CharField(blank=True, default=None, help_text='link to view description in the Learn section', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='layer',
            name='mouseover_field',
            field=models.CharField(blank=True, default=None, help_text='feature level attribute used in mouseover display', max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='layer',
            name='point_radius',
            field=models.IntegerField(blank=True, default=None, help_text='Used only for for Point layers (default is 2)', null=True),
        ),
        migrations.AlterField(
            model_name='layer',
            name='thumbnail',
            field=models.URLField(blank=True, default=None, help_text='not sure we are using this any longer...', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='layer',
            name='wms_version',
            field=models.CharField(blank=True, choices=[(None, ''), ('1.0.0', '1.0.0'), ('1.1.0', '1.1.0'), ('1.1.1', '1.1.1'), ('1.3.0', '1.3.0')], default=None, help_text='WMS Versioning - usually either 1.1.1 or 1.3.0', max_length=10, null=True),
        ),
    ]
