# Generated by Django 3.2.16 on 2022-12-08 22:12

import data_manager.models
import django.contrib.sites.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0052_externalportal'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='layer',
            managers=[
                ('objects', django.contrib.sites.managers.CurrentSiteManager('site')),
                ('all_objects', data_manager.models.AllObjectsManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='theme',
            managers=[
                ('objects', django.contrib.sites.managers.CurrentSiteManager('site')),
                ('all_objects', data_manager.models.AllObjectsManager()),
            ],
        ),
    ]
