# Generated by Django 3.2.16 on 2023-07-03 23:51

import data_manager.models
import django.contrib.sites.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0053_auto_20230703_2345'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='layer',
            managers=[
                ('objects', django.contrib.sites.managers.CurrentSiteManager('site')),
                ('all_objects', data_manager.models.AllObjectsManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='theme',
            managers=[
                ('objects', django.contrib.sites.managers.CurrentSiteManager('site')),
                ('all_objects', data_manager.models.AllObjectsManager()),
            ],
        ),
    ]
