# Generated by Django 3.2.25 on 2025-04-25 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0054_auto_20250425_2139'),
        ('data_manager', '0055_alter_theme_options'),
    ]

    operations = [
    ]
