# Generated by Django 3.2.25 on 2025-04-22 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0054_auto_20250422_2230'),
        ('data_manager', '0055_alter_theme_options'),
    ]

    operations = [
    ]
