# Generated by Django 4.2.17 on 2025-02-12 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0057_layer_last_success_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='last_http_status',
            field=models.CharField(blank=True, help_text='HTTP status code from last check', max_length=100, null=True),
        ),
    ]
