# Generated by Django 4.2.20 on 2025-04-22 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0056_auto_20250418_1913'),
        ('data_manager', '0058_layer_last_http_status'),
    ]

    operations = [
    ]
