# Generated by Django 4.2.20 on 2025-04-23 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_manager', '0056_merge_20250422_2256'),
        ('data_manager', '0058_layer_last_http_status'),
    ]

    operations = [
    ]
